lab1/Controllers/ProjectController.cs
using System.Diagnostics;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TRS.Controllers.Attributes;
using TRS.Controllers.Constants;
using TRS.DataManager;
using TRS.Extensions;
using TRS.Models.DomainModels;
using TRS.Models.ViewModels;

namespace TRS.Controllers
{
    [ForLoggedInOnly]
    public class ProjectController : BaseController
    {
        private ILogger<ProjectController> _logger;

        public ProjectController(IDataManager dataManager, IMapper mapper, ILogger<ProjectController> logger)
            : base(dataManager, mapper)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var userProjectList = DataManager.FindProjectsByManager(LoggedInUser.Name);
            var projectListModel = new ProjectListModel
            {
                Projects = userProjectList.Select(x =>
                {
                    var mappedProject = Mapper.Map<ProjectModel>(x);
                    var totalAcceptedTime = DataManager.FindReportsByProject(x.Code)
                        .SelectMany(y => y.Accepted)
                        .Where(y => y.Code == x.Code)
                        .Sum(y => y.Time);
                    mappedProject.BudgetLeft = x.Budget - totalAcceptedTime;
                    return mappedProject;
                }).ToList()
            };
            return View(projectListModel);
        }

        public IActionResult Show(string id)
        {
            var project = DataManager.FindProjectByCode(id);
            if (project == null)
                return RedirectToActionWithError("Index", ErrorMessages.GetProjectNotFoundMessage(id));
            var projectWithUsersModel = Mapper.Map<ProjectWithUserSummaryModel>(project);
            var reports = DataManager.FindReportsByProject(id);
            var userSummaries = reports.Where(x => x.Frozen).Select(x =>
            {
                var acceptedSummary = x.Accepted.FirstOrDefault(y => y.Code == project.Code);
                return new ProjectWithUserSummaryEntry
                {
                    Username = x.Owner,
                    Month = x.Month,
                    DeclaredTime = x.Entries.Where(y => y.Code == project.Code).Sum(y => y.Time),
                    AcceptedTime = acceptedSummary?.Time
                };
            }).ToList();
            projectWithUsersModel.BudgetLeft = projectWithUsersModel.Budget - userSummaries.Sum(x => x.AcceptedTime ?? 0);
            projectWithUsersModel.UserSummaries = userSummaries;
            return View(projectWithUsersModel);
        }

        public IActionResult Edit(string id)
        {
            var project = DataManager.FindProjectByCode(id);
            if (project == null)
                return RedirectToActionWithError("Index", ErrorMessages.GetProjectNotFoundMessage(id));
            var projectModel = Mapper.Map<ProjectModel>(project);
            return View(projectModel);
        }

        [HttpPost]
        public IActionResult Edit(ProjectModel projectModel)
        {
            if (!ModelState.IsValid)
                return View(projectModel);
            var inputProject = Mapper.Map<Project>(projectModel);
            var modifiedProject = DataManager.FindProjectByCode(projectModel.Code);
            if (modifiedProject == null)
                return RedirectToActionWithError("Index", ErrorMessages.GetProjectNotFoundMessage(projectModel.Code));
            modifiedProject.Budget = inputProject.Budget;
            modifiedProject.Subactivities = inputProject.Subactivities;
            DataManager.UpdateProject(modifiedProject);
            return RedirectToAction("Index");
        }

        public IActionResult Add()
        {
            return View(new ProjectModel());
        }

        [HttpPost]
        public IActionResult Add(ProjectModel projectModel)
        {
            if (!ModelState.IsValid)
                return View(projectModel);
            var duplicatedProject = DataManager.FindProjectByCode(projectModel.Code);
            if (duplicatedProject != null)
                ModelState.AddModelError(nameof(projectModel.Code), ErrorMessages.GetProjectAlreadyExistingMessage(projectModel.Code));
            if (!ModelState.IsValid)
                return View(projectModel);
            projectModel.Manager = LoggedInUser.Name;
            projectModel.Active = true;
            var project = Mapper.Map<Project>(projectModel);
            DataManager.AddProject(project);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Close(string id)
        {
            var project = DataManager.FindProjectByCode(id);
            if (project == null)
                return RedirectToActionWithError("Index", ErrorMessages.GetProjectNotFoundMessage(id));
            project.Active = false;
            DataManager.UpdateProject(project);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult UpdateAcceptedTime(string id, string username, int? acceptedTime)
        {
            var project = DataManager.FindProjectByCode(id);
            if (project == null)
                return RedirectToActionWithError("Index", ErrorMessages.GetProjectNotFoundMessage(id));
            switch (acceptedTime)
            {
                case null:
                    return RedirectToAction("Show", new { Id = id });
                case < 0:
                    return RedirectToActionWithError("Show", new { Id = id }, ErrorMessages.AcceptedTimeNegative);
            }
            var report = DataManager.FindReportByUserAndMonth(username, RequestedDate);
            if (project.Manager != LoggedInUser.Name || report.Entries.All(x => x.Code != id))
                return RedirectToActionWithError("Show", new { Id = id }, ErrorMessages.GetNoAccessToAcceptedTimeMessage(username, RequestedDate.ToMonthString()));
            var accepted = new AcceptedTime { Code = id, Time = acceptedTime.Value };
            DataManager.SetAcceptedTime(username, RequestedDate, accepted);
            return RedirectToAction("Show", new { Id = id });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab1/Controllers/ReportController.cs
using System.Diagnostics;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TRS.Controllers.Attributes;
using TRS.DataManager;
using TRS.Extensions;
using TRS.Models.ViewModels;

namespace TRS.Controllers
{
    [ForLoggedInOnly]
    public class ReportController : BaseController
    {
        private ILogger<ReportController> _logger;

        public ReportController(IDataManager dataManager, IMapper mapper, ILogger<ReportController> logger)
            : base(dataManager, mapper)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var report = DataManager.FindReportByUserAndMonth(LoggedInUser.Name, RequestedDate);
            var summaryEntries = report.Entries.GroupBy(x => x.Code)
                .Select(x => new ProjectTimeSummaryEntry
                {
                    ProjectCode = x.Key,
                    Time = x.Sum(y => y.Time),
                    AcceptedTime = report.Accepted.FirstOrDefault(y => y.Code == x.Key)?.Time
                }).ToList();
            var model = new MonthlySummaryModel
            {
                Month = RequestedDate,
                Frozen = report.Frozen,
                ProjectTimeSummaries = summaryEntries,
                TotalTime = summaryEntries.Sum(x => x.Time),
                TotalAcceptedTime = summaryEntries.Sum(x => x.AcceptedTime ?? 0)
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Freeze()
        {
            DataManager.FreezeReport(LoggedInUser.Name, RequestedDate);
            return RedirectToAction("Index", new { Date = RequestedDate.ToDateString() });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab1/Controllers/UserController.cs
using System.Diagnostics;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using TRS.Controllers.Attributes;
using TRS.Controllers.Constants;
using TRS.DataManager;
using TRS.Models.DomainModels;
using TRS.Models.ViewModels;

namespace TRS.Controllers
{
    public class UserController : BaseController
    {
        private ILogger<UserController> _logger;

        public UserController(IDataManager dataManager, IMapper mapper, ILogger<UserController> logger)
            : base(dataManager, mapper)
        {
            _logger = logger;
        }

        [ForLoggedInOnly]
        public IActionResult Index()
        {
            return View();
        }

        private void FillSelectListsInLoginModel(UserSelectListModel loginModel)
        {
            var usernames = DataManager.GetAllUsers().Select(x => new SelectListItem(x.Name, x.Name)).ToList();
            loginModel.Usernames = usernames;
        }

        [ForNotLoggedInOnly]
        public IActionResult Login()
        {
            var model = new UserSelectListModel();
            FillSelectListsInLoginModel(model);
            return View(model);
        }

        [ForNotLoggedInOnly]
        [HttpPost]
        public IActionResult Login(UserModel user)
        {
            if (!ModelState.IsValid)
                goto InvalidModelState;
            var foundUser = DataManager.FindUserByName(user.Name);
            if (foundUser == null)
                ModelState.AddModelError(nameof(user.Name), ErrorMessages.GetUserNotFoundMessage(user.Name));
            if (!ModelState.IsValid)
                goto InvalidModelState;
            LoggedInUser = foundUser;
            return RedirectToAction("Index", "Home");

        InvalidModelState:
            var loginModel = Mapper.Map<UserSelectListModel>(user);
            FillSelectListsInLoginModel(loginModel);
            return View(loginModel);
        }

        [ForLoggedInOnly]
        [HttpPost]
        public IActionResult Logout()
        {
            LoggedInUser = null;
            return RedirectToAction("NotLoggedIn", "Home");
        }

        [ForNotLoggedInOnly]
        public IActionResult Register()
        {
            return View();
        }

        [ForNotLoggedInOnly]
        [HttpPost]
        public IActionResult Register(UserModel user)
        {
            if (!ModelState.IsValid)
                return Register();
            var existingUser = DataManager.FindUserByName(user.Name);
            if (existingUser != null)
                ModelState.AddModelError(nameof(user.Name), ErrorMessages.GetUserAlreadyExistingMessage(user.Name));
            if (!ModelState.IsValid)
                return Register();
            DataManager.AddUser(new User { Name = user.Name });
            return Login(user);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab1/Views/Shared/_Layout.cshtml
@using TRS.Models.DomainModels
@using TRS.Extensions

@{
    User loggedInUser = null;
    if (ViewData.TryGetValue("user", out var contextUser))
        loggedInUser = (User)contextUser;

    var date = (DateTime)ViewData["date"];
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - TRS</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            @if (loggedInUser != null)
            {
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TRS</a>
            }
            else
            {
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="NotLoggedIn">TRS</a>
            }
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @if (loggedInUser != null)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index" asp-route-date="@date.ToDateString()">Strona główna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Report" asp-action="Index" asp-route-date="@date.ToDateString()">Zestawienie miesięczne</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Project" asp-action="Index">Zarządzane projekty</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="NotLoggedIn">Strona główna</a>
                        </li>
                    }
                </ul>
                <ul class="navbar-nav flex-grow-1 flex-row-reverse">
                    @{
                        if (loggedInUser != null)
                        {
                            <li class="nav-item">
                                <form method="POST">
                                    <button asp-action="Logout" asp-controller="User">Wyloguj się</button>
                                </form>
                            </li>
                            <li>
                                Zalogowany jako @loggedInUser.Name
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Zaloguj się</a>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        <div id="error-container" class="container" hidden>
            @Html.ValidationMessage("error")
        </div>
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - TRS
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
<script type="text/javascript">
    (function () {
        const errorContainer = document.getElementById('error-container');
        if (errorContainer.querySelector('.field-validation-error') != null)
            errorContainer.hidden = false;
    })();
</script>
</body>
</html>