lab1/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TRS.Controllers.Attributes;
using TRS.DataManager;
using TRS.Models.ViewModels;

namespace TRS.Controllers
{
    public class HomeController : BaseController
    {
        private ILogger<HomeController> _logger;

        public HomeController(IDataManager dataManager, IMapper mapper, ILogger<HomeController> logger)
            : base(dataManager, mapper)
        {
            _logger = logger;
        }

        [ForLoggedInOnly]
        public IActionResult Index()
        {
            var report = DataManager.FindReportByUserAndMonth(LoggedInUser.Name, RequestedDate);
            var reportEntries = report.Entries.Where(x => x.Date == RequestedDate).ToList();
            return View(new DailyReportModel
            {
                Frozen = report.Frozen,
                Entries = Mapper.Map<List<ReportEntryModel>>(reportEntries),
                ProjectTimeSummaries = reportEntries.GroupBy(x => x.Code)
                    .Select(x => new ProjectTimeSummaryEntry
                    {
                        ProjectCode = x.Key,
                        Time = x.Sum(y => y.Time)
                    }).ToList(),
                TotalTime = reportEntries.Sum(x => x.Time)
            });
        }

        [ForNotLoggedInOnly]
        public IActionResult NotLoggedIn() => View();

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab1/Controllers/ReportEntryController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using TRS.Controllers.Attributes;
using TRS.Controllers.Constants;
using TRS.DataManager;
using TRS.DataManager.Exceptions;
using TRS.Extensions;
using TRS.Models.DomainModels;
using TRS.Models.ViewModels;

namespace TRS.Controllers
{
    [ForLoggedInOnly]
    public class ReportEntryController : BaseController
    {
        private ILogger<ReportEntryController> _logger;

        public ReportEntryController(IDataManager dataManager, IMapper mapper, ILogger<ReportEntryController> logger)
            : base(dataManager, mapper)
        {
            _logger = logger;
        }

        public IActionResult Show(int id)
        {
            var reportEntry = DataManager.FindReportEntryByDayAndIndex(LoggedInUser.Name, RequestedDate, id);
            if (reportEntry == null)
                return RedirectToActionWithError("Index", "Home", new { Date = RequestedDate.ToDateString() }, ErrorMessages.GetReportEntryNotFoundMessage(RequestedDate, id));
            return View(Mapper.Map<ReportEntryModel>(reportEntry));
        }

        private void FillSelectListsInEditingModel(ReportEntryForEditingModel editingModel, string projectCode)
        {
            var project = DataManager.FindProjectByCode(projectCode);
            var categoryCodes = project.Subactivities.Select(y => new SelectListItem(y.Code, y.Code)).ToList();
            editingModel.CategorySelectList = categoryCodes;
        }

        public IActionResult Edit(int id)
        {
            if (DataManager.FindReportByUserAndMonth(LoggedInUser.Name, RequestedDate).Frozen)
                return RedirectToActionWithError("Index", "Home", new { Date = RequestedDate.ToDateString() }, ErrorMessages.GetReportFrozenMessage(RequestedDate.ToMonthString()));
            var reportEntry = DataManager.FindReportEntryByDayAndIndex(LoggedInUser.Name, RequestedDate, id);
            if (reportEntry == null)
                return RedirectToActionWithError("Index", "Home", new { Date = RequestedDate.ToDateString() }, ErrorMessages.GetReportEntryNotFoundMessage(RequestedDate, id));
            var model = Mapper.Map<ReportEntryForEditingModel>(reportEntry);
            FillSelectListsInEditingModel(model, reportEntry.Code);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(int id, ReportEntryModel reportEntry)
        {
            if (!ModelState.IsValid)
            {
                var editingModel = Mapper.Map<ReportEntryForEditingModel>(reportEntry);
                FillSelectListsInEditingModel(editingModel, reportEntry.Code);
                return View(editingModel);
            }
            if (DataManager.FindReportByUserAndMonth(LoggedInUser.Name, RequestedDate).Frozen)
                return RedirectToActionWithError("Index", "Home", new { Date = RequestedDate.ToDateString() }, ErrorMessages.GetReportFrozenMessage(RequestedDate.ToMonthString()));
            var updatedReportEntry = DataManager.FindReportEntryByDayAndIndex(LoggedInUser.Name, RequestedDate, id);
            if (updatedReportEntry == null)
                return RedirectToActionWithError("Index", "Home", new { Date = RequestedDate.ToDateString() }, ErrorMessages.GetReportEntryNotFoundMessage(RequestedDate, id));
            updatedReportEntry.Subcode = reportEntry.Subcode;
            updatedReportEntry.Time = reportEntry.Time;
            updatedReportEntry.Description = reportEntry.Description;
            DataManager.UpdateReportEntry(LoggedInUser.Name, RequestedDate, id, updatedReportEntry);
            return RedirectToAction("Index", "Home", new { Date = RequestedDate.ToDateString() });
        }

        private void FillSelectListsInAddingModel(ReportEntryForAddingModel addingModel)
        {
            var availableProjects = DataManager.GetAllProjects().Where(x => x.Active).ToHashSet();
            var projectCodes = availableProjects.Select(x => new SelectListItem( $"{x.Name} ({x.Code})", x.Code)).ToList();
            var categoryCodes = availableProjects.ToDictionary(x => x.Code,
                x => x.Subactivities.Select(y => new SelectListItem(y.Code, y.Code)).ToList());
            addingModel.ProjectSelectList = projectCodes;
            addingModel.ProjectCategorySelectList = categoryCodes;
        }

        public IActionResult Add()
        {
            if (DataManager.FindReportByUserAndMonth(LoggedInUser.Name, RequestedDate).Frozen)
                return RedirectToActionWithError("Index", "Home", new { Date = RequestedDate.ToDateString() }, ErrorMessages.GetReportFrozenMessage(RequestedDate.ToMonthString()));
            var model = new ReportEntryForAddingModel { Date = RequestedDate };
            FillSelectListsInAddingModel(model);
            return View(model);
        }

        [HttpPost]
        public IActionResult Add(ReportEntryModel reportEntry)
        {
            if (!ModelState.IsValid)
                goto InvalidModelState;
            if (DataManager.FindReportByUserAndMonth(LoggedInUser.Name, reportEntry.Date).Frozen)
                return RedirectToActionWithError("Index", "Home", new { Date = reportEntry.Date.ToDateString() }, ErrorMessages.GetReportFrozenMessage(reportEntry.Date.ToMonthString()));
            var project = DataManager.FindProjectByCode(reportEntry.Code);
            switch (project)
            {
                case null:
                    ModelState.AddModelError(nameof(reportEntry.Code), ErrorMessages.GetProjectNotFoundMessage(reportEntry.Code));
                    break;
                case { Active: false }:
                    ModelState.AddModelError(nameof(reportEntry.Code), ErrorMessages.GetProjectNoLongerActiveMessage(reportEntry.Code));
                    break;
            }
            if (!ModelState.IsValid)
                goto InvalidModelState;
            DataManager.AddReportEntry(LoggedInUser.Name, Mapper.Map<ReportEntry>(reportEntry));
            return RedirectToAction("Index", "Home", new { Date = reportEntry.Date.ToDateString() });

        InvalidModelState:
            var addingModel = Mapper.Map<ReportEntryForAddingModel>(reportEntry);
            FillSelectListsInAddingModel(addingModel);
            return View(addingModel);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            if (DataManager.FindReportByUserAndMonth(LoggedInUser.Name, RequestedDate).Frozen)
                return RedirectToActionWithError("Index", "Home", new { Date = RequestedDate.ToDateString() }, ErrorMessages.GetReportFrozenMessage(RequestedDate.ToMonthString()));
            try
            {
                DataManager.DeleteReportEntry(LoggedInUser.Name, RequestedDate, id);
            }
            catch (NotFoundException)
            {
                return RedirectToActionWithError("Index", "Home", new { Date = RequestedDate.ToDateString() }, ErrorMessages.GetReportEntryNotFoundMessage(RequestedDate, id));
            }
            return RedirectToAction("Index", "Home", new { Date = RequestedDate.ToDateString() });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab1/Views/Home/Index.cshtml
@using TRS.Extensions
@model TRS.Models.ViewModels.DailyReportModel

@{
    ViewData["Title"] = "Strona główna";
    var date = (DateTime)ViewData["date"];
}

<main class="bd-main order-1 gap-3">
    <div class="d-md-flex align-items-center justify-content-between">
        <h1 class="display-6">Raport czasu pracy na dzień @date.ToDateString()</h1>
        <form asp-action="Index" method="GET">
            <span>Przejdź do: </span>
            <input name="date" type="date" value="@date.ToDateString()"/>
            <input type="submit" value="Wyślij"/>
        </form>
    </div>
    <div class="text-center">
        <table class="table">
            <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Entries[0].Code)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Entries[0].Subcode)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Entries[0].Time)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Entries[0].Description)
                </th>
                <th>
                    Akcje
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach (var entry in Model.Entries)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(model => entry.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(model => entry.Subcode)
                    </td>
                    <td>
                        @Html.DisplayFor(model => entry.Time)
                    </td>
                    <td>
                        @Html.DisplayFor(model => entry.Description)
                    </td>
                    <td>
                        <a asp-controller="ReportEntry" asp-action="Show" asp-route-date="@date.ToDateString()" asp-route-id="@entry.MonthlyIndex">Obejrzyj</a>
                        @if (!Model.Frozen)
                        {
                            <a asp-controller="ReportEntry" asp-action="Edit" asp-route-date="@date.ToDateString()" asp-route-id="@entry.MonthlyIndex">Zmień</a>
                            <form method="POST">
                                <button asp-controller="ReportEntry" asp-action="Delete" asp-route-date="@date.ToDateString()" asp-route-id="@entry.MonthlyIndex">Skasuj</button>
                            </form>
                        }
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
    @if (!Model.Frozen)
    {
        <p>
            <a asp-controller="ReportEntry" asp-action="Add" asp-route-date="@date.ToDateString()">Dodaj</a>
        </p>
    }
    <p>
        <strong>Podsumowanie dzienne</strong>
    </p>
    <table class="table">
        <tbody>
        @foreach (var summaryEntry in Model.ProjectTimeSummaries)
        {
            <tr>
                <td>
                    @summaryEntry.ProjectCode
                </td>
                <td>
                    @summaryEntry.Time
                </td>
            </tr>
        }
        <tr><td></td><td></td></tr>
        <tr>
            <td>
                Razem
            </td>
            <td>
                @Model.TotalTime
            </td>
        </tr>
        </tbody>
    </table>
</main>

lab1/Views/Home/IndexNotLoggedIn.cshtml
@model TRS.Models.ViewModels.DailyReportModel

@{
    ViewData["Title"] = "Strona główna";
}

<main class="bd-main order-1 gap-3">
    <div class="text-center">
        <h1 class="display-6">Witaj na stronie głównej systemu TRS</h1>
    </div>
</main>